### ISSUE TITLE
Inverse and eigen methods on matrix

### ISSUE THREAD

**Issue by dineshadepu** [termhn/ultraviolet#1]
Thanks for the crate. I am looking for a methods which implements `inverse`, `eigenvalues`, `eigenvectors`. Are these supported?

**Comment by termhn** [comment]
Currently they are not, no. Good things to support though, so I'll add them to the list of things to implement.

**Comment by termhn** [comment]
Inverses are now implemented; I'm leaving out eigenvalues and eigenvectors because I want to focus this lib on games and computer graphics specifically, and those things are not really useful in that context.
