### ISSUE TITLE
Conversion from Mat4 to Mat3

### ISSUE THREAD

**Issue by expenses** [termhn/ultraviolet#100]
It'd be nice to have a helper function to convert from a `Mat4` to a `Mat3` by taking the top-left corner of the matrix.

**Comment by termhn** [comment]
Agreed, not sure what the naming scheme should be. I personally like `truncate` though some others didn't like that, maybe just `to_mat3`?

**Comment by expenses** [comment]
`truncate` would be fine for documentation but pretty vague if you're just reading someone's code with type inference. I think being explicit about the what part of the 4x4 matrix is used would be good. Is there a good name for that top-left 3x3 matrix? Maybe something like `to_top_left_mat3` or is that too long?

**Comment by swiftcoder** [comment]
Would it make sense to follow the same naming pattern as `extract_rotation()`, since it's effectively the same operation?
