### ISSUE TITLE
`Neg` trait for `IVec`

### ISSUE THREAD

**Issue by SnootierMoon** [termhn/ultraviolet#133]
I noticed that the `Neg` trait was missing for the `IVec` types. This isn't that big of an issue because I can do `vec * -1` instead, but it still seems like a mistake. I compared the trait implementations of `IVec3` with `Vec3`, and `Neg` seems to be the only reasonable one that's missing.

Also, I love this crate and it's really fun to use, so thank you for making it :))

**Comment by SnootierMoon** [comment]
After looking at `int.rs`, I realized that the `IVec` and `UVec` types are defined from the same macros, so it might take a bit of refactoring to implement the `Neg` traits for the signed vectors.

**Comment by SnootierMoon** [comment]
Oops, I accidentally closed the issue. I'm somewhat new to using GitHub.

**Comment by termhn** [comment]
Good spot. For ones that only work for IVec you can just add them outside the macro (this happens in a few other places as well).

**Comment by SnootierMoon** [comment]
Fixed by #134
