### ISSUE TITLE
Matrix serialization is length-delimited but deserialization isn't

### ISSUE THREAD

**Issue by danielkeller** [termhn/ultraviolet#138]
For example, with `bincode`, the following assertion fails:

```rust
let unit = Mat4::identity();
assert_eq!(
    unit,
    bincode::deserialize::<Mat4>(&bincode::serialize(&unit).unwrap()).unwrap()
);
```

It looks like the serializer inserts a length that the deserializer doesn't read.

**Comment by AlphaModder** [comment]
This occurs because the `Serialize` impl calls `serialize_seq` but the `Deserialize` impl calls `deserialize_tuple`. `ron` is also affected. I have opened a PR #140 to fix this.
