### ISSUE TITLE
Possibly change Default implementations to be closer to 'identity' rather than just uniformly zero

### ISSUE THREAD

**Issue by termhn** [termhn/ultraviolet#14]
Currently, Default implementations simply make all values zero. This is concise and clean from a memory standpoint but can result in some possibly unintuitive behavior and, more importantly, invalid values of some constructs being created by Default. For example, Rotors should always have a norm of one, but currently upon being constructed by Default::default, they will have norm of 0 which is invalid. Similarly for square matrices, perhaps Default should create identity matrices.

**Comment by khionu** [comment]
Default values should be valid, doesn't make any sense for a library to produce a object that is somehow invalid.

**Comment by azriel91** [comment]
I find the all zero transform in Amethyst a gotcha, so would prefer the "it makes more sense for a user than a computer" approach.

**Comment by termhn** [comment]
This has been changed, Default now redirects to identity() where it makes sense. Vectors and Bivectors still have zero for default initialization, which I think makes most sense.
