### ISSUE TITLE
Consider releasing v0.8.2

### ISSUE THREAD

**Issue by teoxoy** [termhn/ultraviolet#141]
Due to `wide v0.6.x` not compiling successfully when using `-Z minimal-versions` it has been bumped to 0.7 in https://github.com/termhn/ultraviolet/pull/135 but no release has been made yet that includes this change.

**Comment by termhn** [comment]
This is technically a breaking change so will release as `0.9.0` :) Thanks for the reminder

**Comment by termhn** [comment]
Release done!
