### ISSUE TITLE
Implement PartialEq trait to compare vector types

### ISSUE THREAD

**Issue by Skytrias** [termhn/ultraviolet#21]
Hey i really like ultraviolet so far, havent used any simd yet but will at some point.

Was just wondering if it would be possible to implement the PartialEq trait in the macro that generates the vectors? I use comparisons a lot on vectors and was surprised it didnt exist.

**Comment by termhn** [comment]
It's not possible to implement PartialEq for the wide vector types, but it is for the regular ones. This is something that probably should get done I just sorta shunted it cause I wasn't sure if there was a better solution for both the wide and regular types. But I think the regular scalar types should definitely impl PartialEq

**Comment by termhn** [comment]
Fixed by #38
