### ISSUE TITLE
Serde for Vec and Mat

### ISSUE THREAD

**Issue by MagicRB** [termhn/ultraviolet#23]
It would be really nice to have serde support behind a feature for the it makes sense for, I could only find Vec and Mat, though I might be missing some.

**Comment by MagicRB** [comment]
I'm going to try to take this up, shouldn't be that hard I suppose.

**Comment by MagicRB** [comment]
I need help with making a special case for the wide types, since they don't have `Serialize` and `Deserialize` implemented.

**Comment by termhn** [comment]
Just impl them outside the macros only for the non wide types

**Comment by MagicRB** [comment]
PR #25 is in, as I stated in the PR, it's not really tested, but it should work, aka there is no reason why it shouldn't

**Comment by termhn** [comment]
Fixed by #38
