### ISSUE TITLE
Any plans for f64 support?

### ISSUE THREAD

**Issue by Sorrien** [termhn/ultraviolet#28]
I understand wanting to avoid generics and how f64 would negatively impact SIMD speed. I believe there are plenty of use cases that make support for f64 based types worth adding, even if it involved making separate types for those to avoid using generics.

**Comment by termhn** [comment]
I'm not directly opposed to it. However, it's not something I personally care about, and probably won't be implemented (by me, at least) until I find a use that I do care about.

**Comment by Sorrien** [comment]
That's fair. Hopefully I or someone else will be able to make a pull request in the future and we can circle back to the question. I would do it now, but I don't think my macro mastery is there just yet.

**Comment by virtualritz** [comment]
I love this crate!
I would throw out `nalgebra` tomorrow but the stuff I write is for CGI. And in this use case coordinates commonly use f32 but matrices are all f64. So I'm really interested in this too.

**Comment by DzmitryFil** [comment]
+1 for f64 support. It's a showstopper for me, as my work requires huge world coordinates which are converted to relative_to_camera f32 at render time only.

**Comment by termhn** [comment]
(untested) f64 support has now landed in 3711a6f5207eded3b1e2c7b9128d2d41736e364f under the `nightly` feature (nightly rust compiler only)! Support under stable compiler versions should be in before I release to crates.io, however stable will only support `f64` and `f64x2` for now. `f64x4` and higher is nightly-only for the foreseeable future.

I'm going to leave this issue open for feedback until the next version lands on crates.io!

Ping @DzmitryFil @virtualritz @Sorrien :)

**Comment by Sorrien** [comment]
You rock @termhn

**Comment by termhn** [comment]
Started implementing some benchmarks on top of @sebcrozet 's fork of mathbench to test vs the new SIMD'd nalgebra; added some f64 tests for both. Both within margin of error on this laptop considering the conditions for the benches weren't optimal :p 

https://gist.github.com/termhn/1b03955a618dfe5ed6c3ac647f36169b

**Comment by termhn** [comment]
Alright, I'm closing this as f64s seem to work properly. Release soon! Just need to finish making benches and then do a release post...
