### ISSUE TITLE
Mat4.translate() not working or unintuitive?

### ISSUE THREAD

**Issue by mgimle** [termhn/ultraviolet#34]
https://github.com/termhn/ultraviolet/blob/f09d279f99fbb1e941952575afa1f539a2b9a901/src/mat.rs#L1099-L1102

I tried calling `translate` on a Mat4 and noticed that the end result was not at all what I was expecting it to be.

I would have expected the matrix to represent a translation along the provided vector after calling the function, but upon inspecting the source code I saw that this doesn't seem to be the case at all. 

Is the translation done here some other kind of mathematical operation I'm not aware of (I failed to find anyhting suggesting this after looking around a bit), or is this code not in a functioning state?

It seems to me that changing only a single value in the matrix can't possibly be called translation, so this code is confusing me quite a bit.

**Comment by termhn** [comment]
Sorry for taking a while to get to this... Hm, yeah that looks wrong. Must have broken at some point during the indexing refactor.

**Comment by termhn** [comment]
Fixed in 43986a5dcaa0be85e86e9b2f7d72e5fb7d34316d
