### ISSUE TITLE
Built-in support for wgpu

### ISSUE THREAD

**Issue by lachlansneff** [termhn/ultraviolet#37]
Including built-in support for [wgpu](https://github.com/gfx-rs/wgpu-rs) for functions like `projection_wgpu` and that kind of thing would be really nice. It's easy to fix it by just multiplying by a correction matrix, but it's not quite convenient.

**Comment by termhn** [comment]
Done in d6d2996db5ef0a0ca9904b1420ca5e0b1eb8aa45#diff-25d902c24283ab8cfbac54dfa101ad31
