### ISSUE TITLE
`Similarity{N}::into_homogeneous_matrix` ignores scale

### ISSUE THREAD

**Issue by zakarumych** [termhn/ultraviolet#41]
This function constructs matrix from `translation` component and multiplies by matrix made of `rotation` component. I guess `scale` component should be used as well.

**Comment by zakarumych** [comment]
`Isometry{N}` has same issue.

**Comment by termhn** [comment]
> `Isometry{N}` has same issue.

Isometry doesnt have scale so that doesn't apply, but you're right that Similarity are not working correctly.

**Comment by termhn** [comment]
Fixed in 58c4506
