### ISSUE TITLE
Union of Aabb

### ISSUE THREAD

**Issue by kaoet** [termhn/ultraviolet#58]
Assume we have:
```rust
let a = Aabb::new(Vec3::new(0, 0, 0), Vec3::new(2, 2, 2));
let b = Aabb::new(Vec3::new(-1, -1, -1), Vec3::new(1, 1, 1));
```

Can we have function `union`:
```rust
union(a, b) == Aabb::new(Vec3::new(-1, -1, -1), Vec3::new(2, 2, 2))
```

**Comment by termhn** [comment]
This is a good idea! However, I've decided to remove the `geometry` module from `ultraviolet` itself and rather have it as a separate crate. see https://github.com/termhn/ultraviolet/pull/33#issuecomment-691226204 for more
