### ISSUE TITLE
Implement a Mat3 -> Rotor3 conversion ?

### ISSUE THREAD

**Issue by thenlevy** [termhn/ultraviolet#61]
The possibility to convert a rotation matrix into a rotor could be usefull.
The problem is that such a conversion might not always make sense if the matrix is not a rotation matrix.
One could

* Have a method `Mat3::to_rotor3(&self) -> Option<Rotor3>` that would test if `self` is actually a rotation (slow and returns an `Option`)
* Return garbage if the matrix is not a rotation and be explicit about it in the documentation.

Here is how the Matrix -> Quaternion is done in [cgmath](https://docs.rs/cgmath/0.17.0/src/cgmath/matrix.rs.html#1475-1516)

**Comment by termhn** [comment]
This would definitely be useful yes. Here's an article discussing how it works for Quaternions (which are directly isomorphic to Rotor3s, just setup slightly different). I'm partial to the "alternative method" about half way down the page as it requires no branching and therefore could be used for both scalar and wide versions without modification 

Also for that reason, I would say it's better to just require the caller to be certain their matrix is suitable and potentially return garbage if it's not.

**Comment by thenlevy** [comment]
Assuming you were referring to [this article](http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/) there is a discussion on how the use of `copysign` might gives a wrong result when `copysign` is called on 0. In rust, floats have a `copysign` method that multiply by either 1 or - 1 but never by 0, so testing might be necessary

**Comment by termhn** [comment]
Fixed by #63
