### ISSUE TITLE
Addition and scalar multiplication of matrices.

### ISSUE THREAD

**Issue by rtavenner** [termhn/ultraviolet#62]
I notice that these `impl`s are missing:

- `impl Add for MatN` (and probably `AddAssign` as well)
- `impl Mul<f32> for MatN`

Admittedly, these aren't the most common operations, but they do come up occasionally, and it seems weird that they're missing.

There is a workaround, but it's a bit annoying; split the matri(x/ces) into (its/their) component vectors, and apply the operation separately on each component.

**Comment by termhn** [comment]
Yep these are definitely good to have. They don't exist mostly cause myself nor anyone else using it has wanted it so far... Or at least hasnt reported wanting it :p

**Comment by termhn** [comment]
Implemented in bfd963332862129ab8b8e56a9b92f64ad332773d and released as 0.6.1
