### ISSUE TITLE
Mat3::from_nonuniform_scale_homogeneous should take Vec2D instead of Vec3D

### ISSUE THREAD

**Issue by negamartin** [termhn/ultraviolet#69]
Currently the Z value is unused.

**Comment by termhn** [comment]
Fixed in 044469548e9394f13190a72fa5e1bf76834d754b and will be released in 0.7

**Comment by negamartin** [comment]
Great!

By the way, good work! A simplified algebra library like this is ideal for some use cases. It's now my go-to algebra library 😬.

**Comment by termhn** [comment]
Thank you! Glad you find it useful :)
