### ISSUE TITLE
Feature: Mat2/3/4::adjugate method

### ISSUE THREAD

**Issue by negamartin** [termhn/ultraviolet#70]
The adjugate is just like the inverse, but not scaled by the inverse of the determinant.
It can be used as a more efficient alternative to the inverse when working with homogeneous matrices (since multiplication by a scalar has no effect on homogeneous coordinates), saving a determinant and a division operation.

Might be worth considering.

**Comment by termhn** [comment]
Added in aff2b80f1d275b0049c73b82cd472ec6823ccf6b and will be released in 0.7 :)

**Comment by negamartin** [comment]
Thanks for the quick work!
