### ISSUE TITLE
Implement `serde::Serialize` and `serde::Deserialize` for bivec and rotor types

### ISSUE THREAD

**Issue by thenlevy** [termhn/ultraviolet#74]
The serde traits are implemented for the vectors and matrices types. I think it would be usefull to have them also for bivec and rotor types.

I can try to write these implementations, using those of vector and matrices as model.

**Comment by ritobanrc** [comment]
Yes, I would appreciate this as well.

**Comment by joeftiger** [comment]
Actually, on 0.7.1, serde is not used at all (as far as I can see).
As de-/serialization is crucial for me, I might opt for another crate, even though I really like this one.

**Comment by termhn** [comment]
> Actually, on 0.7.1, serde is not used at all (as far as I can see), even for Vec3's.
> As de-/serialization is crucial for me, I might opt for another crate, even though I really like this one.

Support for serialization is gated under the `serde` feature, as noted in the readme. Currently it supports only scalar vector and matrix types, and the above pr will add support for rotors and bivectors.

**Comment by joeftiger** [comment]
> Support for serialization is gated under the `serde` feature, as noted in the readme. Currently it supports only scalar vector and matrix types, and the above pr will add support for rotors and bivectors.

Yes, my bad. I am still new to Rust and don't know how to enable the optional dependencies. I am sorry :-)

**Comment by joeftiger** [comment]
Thank you very much! FIgured it out :-)

**Comment by termhn** [comment]
#75 merged and released as 0.7.2
