### ISSUE TITLE
Unclear documentation for "angle" parameters

### ISSUE THREAD

**Issue by joeftiger** [termhn/ultraviolet#84]
When creating rotations (`Rotor`, etc.), the methods use a parameter `angle`, which is not described as being in radians or degrees.

This could be cleared up, as the user has either to go to the source code to determine the implementation, or use the old try-and-error approach.

**Comment by termhn** [comment]
Fair. I tend to think of radians as pretty ubiquitous, but a PR for this change would be welcome :)

**Comment by joeftiger** [comment]
I'll create a PR once I have time and motivation :-)
Latter is a bit down due to Corona.

**Comment by termhn** [comment]
Absolutely, same heh
