### ISSUE TITLE
Impl PartialEq for Vec3x4 and other SIMD vectors

### ISSUE THREAD

**Issue by joeftiger** [termhn/ultraviolet#87]
I noticed that `PartialEq` is only implemented for Vec3 and f32x4, etc. but not for Vec3x4.
It would make using them in macros and tests much easier. 

```rust
error[E0369]: binary operation `==` cannot be applied to type `Vec3x4`
```

**Comment by termhn** [comment]
This is actually already in on git master from #83 !
